### ISSUE TITLE
avoid sending messages to the same chain

### ISSUE THREAD

**Issue by teterabOb** [ava-labs/teleporter#619] opened 2024-10-20 07:30 UTC
**Context**

During our participation in the Avalanche Summit hackathon, we implemented Teleporter to send cross-chain messages. However, we identified an issue: by mistake, we sent a message to the same chain where the sender contract was deployed. Although the `sendCrosschainMessage` event was emitted successfully, there is no validation preventing messages from being sent to the same chain of origin.

**Proposed Solution**

Since Solidity allows retrieving the chainId using `block.chainid`, it would be great to implement a library that verifies whether the hexadecimal ID of the destination chain differs from the source chain. This validation would prevent human errors when entering the destination chain ID incorrectly and would greatly improve the developer experience by making transaction debugging easier.

**Comment by cam-schultz** [comment] 2024-10-22 14:16
I think this check would be better suited for the Teleporter application, rather than the Teleporter protocol. Teleporter and ICM as protocols are designed to be as flexible as possible, and disallowing sending Teleporter messages to the same chain would be overly restrictive.

Unrelated, but since you mentioned it, `block.chainid` returns the EVM chain ID, not the Avalanche blockchainID. Avalanche blockchain IDs are unique across all Avalanche L1s, and are used by ICM to authenticate senders. The Avalanche blockchain ID can be retreived by calling the Warp precompile method `getBlockchainID`.

**Comment by cam-schultz** [comment] 2024-10-22 20:11
> However, I wonder: in what scenario would it be necessary for a cross-chain messaging protocol to send a message where the destination blockchain is the same as the origin?

Without getting too philisophical, lack of a concrete use case is not reason to disallow such a use case altogether. It's impossible to predict all of the use cases of a new technology. By way of analogy, `localhost` loopback has lots of applications in web2 application development, which would not be possible with an overly restrictive messaging protocol.

It's worth pointing out that the `destinationBlockchainID` is emitted in the `SendCrossChainMessage` event: https://github.com/ava-labs/teleporter/blob/main/contracts/teleporter/ITeleporterMessenger.sol#L63. Decoding that event would be a good first step for troubleshooting unexpected behavior.

**Comment by cam-schultz** [comment] 2024-10-24 21:44
Closing this out as not planned. Please do continue to open issues from a devX perspective. Even if they don't result in protocol changes, they highlight pain points and blind spots in our tooling.

**Closed by cam-schultz** 2024-10-24 21:44 UTC
Labels: enhancement

**Comment by teterabOb** [comment] 2024-10-25 00:56
> Closing this out as not planned. Please do continue to open issues from a devX perspective. Even if they don't result in protocol changes, they highlight pain points and blind spots in our tooling.

Thanks cam , will do
