### ISSUE TITLE
Validator claiming rewards early

### ISSUE THREAD

**Issue by feuGeneA** [ava-labs/teleporter#512] opened 2024-08-29 14:40 UTC
**Context and scope**
The current conception of the staking contracts is that a validator cannot take their rewards until they end their validation period.

**Open questions**
Is there a way we can allow validators to claim their accrued rewards before the end of their validation period?

**Comment by geoff-vball** [comment] 2024-10-31 21:57
Duplicate of https://github.com/ava-labs/teleporter/issues/526

**Closed by geoff-vball** 2024-10-31 21:57 UTC
Labels: enhancement, L1 Staking Contract
